from playwright.async_api import Page


async def expurgo (page: Page, id_user: str, id_interno: str) -> None:
    
    await page.goto(url=f"./ultra/courses/{id_interno}/outline")
    await page.wait_for_load_state('load')
    await page.wait_for_timeout(2*1000)
    await page.get_by_role("link", name="Participantes Visualizar").click()
    await page.wait_for_load_state('load')
    await page.wait_for_timeout(2*1000)
    await page.get_by_role("button", name="Nome ou Sobrenome").click()
    await page.wait_for_load_state('load')
    await page.wait_for_timeout(2*1000)
    await page.get_by_placeholder("Nome ou Sobrenome").click()
    await page.wait_for_load_state('load')
    await page.wait_for_timeout(2*1000)
    # await page.get_by_placeholder("Nome ou Sobrenome").fill("dhiego.moura")
    await page.get_by_placeholder("Nome ou Sobrenome").fill(id_user)
    await page.wait_for_load_state('load')
    await page.wait_for_load_state('domcontentloaded')
    await page.press('body', 'Enter')
    await page.press('#search-roster-field', 'Enter')
    await page.get_by_placeholder("Nome ou Sobrenome").press("Enter")
    try:
        await page.locator('#rosterView-list > ul > li > div > div.medium-5.columns > div > div').click(timeout=3*1000)
        await page.wait_for_load_state('load')
        await page.locator('#roster-settings > ng-form > div.nested-panel > div > div > div.element-card.account > button').click()
        await page.locator('body > div.panel-has-focus > div > footer > div > div.reveal-modal__footer-buttons > span:nth-child(2) > button').click()
        await page.wait_for_load_state('load')
        await page.wait_for_load_state('domcontentloaded')
        await page.wait_for_load_state('networkidle')
        await page.wait_for_timeout(1500)
    except Exception as e:
        await page.locator('#rosterView-grid > ul > li > div > a > bb-username > bb-ui-username > div > div').click(timeout=3*1000)
        await page.wait_for_load_state('load')
        await page.locator('#roster-settings > ng-form > div.nested-panel > div > div > div.element-card.account > button').click()
        await page.locator('body > div.panel-has-focus > div > footer > div > div.reveal-modal__footer-buttons > span:nth-child(2) > button').click()
        await page.wait_for_load_state('load')
        await page.wait_for_load_state('domcontentloaded')
        await page.wait_for_load_state('networkidle')
        await page.wait_for_timeout(1500)
    await page.wait_for_load_state('load')
    await page.wait_for_timeout(2*1000)
    await page.get_by_label("Remover membro").click()
    await page.wait_for_load_state('load')
    await page.wait_for_timeout(2*1000)
    await page.get_by_role("button", name="Remover membro").click()