name: Continuous Integration

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'Master'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # - name: Use Python 3.12
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.12'

      # - name: Install dependencies
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate
      #     pip install --upgrade pip
      #     pip install -r requirements.txt --force-reinstall
      #     python -m playwright install
      #     python -m spacy download pt_core_news_sm

      - name: Fetch tags
        run: git fetch --tags

      - name: Determine next version
        id: next_version
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          
          IFS='.' read -r -a parts <<< "${latest_tag#v}"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          patch=$((patch + 1))
          new_tag="v$major.$minor.$patch"
          echo "New tag: $new_tag"
          
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Check if tag already exists
        run: |
          if git rev-parse "${{ env.NEW_TAG }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.NEW_TAG }} already exists. Aborting."
            exit 1
          fi

      - name: Create a new tag
        run: |
          git tag -a ${{ env.NEW_TAG }} -m "CI release ${{ env.NEW_TAG }}"
          git push origin ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required to push the tag
